### ISSUE TITLE
Comment containing `returns` keyword fails to parse 

### ISSUE THREAD

**Issue by valeneiko** [oguimbal/pgsql-ast-parser#100]
Parsing:
```sql
/*
returns: in a comment
*/
```

Fails with:
```js
Error: invalid syntax at line 2 col 8:

  returns: in a comment
         ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

    - A "semicolon" token
    - A "kw_create" token
    - A "kw_create" token
    - A "kw_create" token
    - A "kw_create" token
    - A "kw_create" token
    - A "word" token
    - A "word" token
    - A "kw_with" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "kw_create" token
    - A "kw_create" token
    - A "word" token
    - A "kw_create" token
    - A "word" token
    - A "word" token
    - A "kw_create" token
    - A "kw_do" token
    - A "kw_select" token
    - A "word" token
    - A "kw_with" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "word" token
    - A "lparen" token


    at Parser.feed (/src/node_modules/nearley/lib/nearley.js:295:27)
    at _parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:110:16)
    at doParse (/src/node_modules/pgsql-ast-parser/src/parser.ts:57:27)
    at Object.parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:60:11)
```

**Comment by oguimbal** [comment]
Should be fixed in ` pgsql-ast-parser@11.0.0`
