### ISSUE TITLE
`DROP TRIGGER` statements fail to parse

### ISSUE THREAD

**Issue by valeneiko** [oguimbal/pgsql-ast-parser#105]
Parsing:
```sql
DROP TRIGGER bar on foo;
```

Fails with:
```js
Error: Syntax error at line 1 col 14:

  DROP TRIGGER bar
               ^
Unexpected word token: "bar". I did not expect any more input. Here is the state of my parse table:

    kw_index → %word ● 
    kw_type → %word ● 
    kw_sequence → %word ● 
    kw_function → %word ● 

    at Parser.feed (/src/node_modules/nearley/lib/nearley.js:343:27)
    at _parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:110:16)
    at doParse (/src/node_modules/pgsql-ast-parser/src/parser.ts:57:27)
    at Object.parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:60:11)
```

**Comment by oguimbal** [comment]
Should be fixed in ` pgsql-ast-parser@11.0.0`
