### ISSUE TITLE
`CASCADE` keyword fails to parse

### ISSUE THREAD

**Issue by valeneiko** [oguimbal/pgsql-ast-parser#107]
Parsing:
```sql
ALTER TABLE foo DROP bar CASCADE;
```

Fails with:
```js
Error: Syntax error at line 1 col 26:

  ALTER TABLE foo DROP bar CASCADE
                           ^
Unexpected word token: "cascade". Instead, I was expecting to see one of the following:

    - A "comma" token
    - A "semicolon" token


    at Parser.feed (/src/node_modules/nearley/lib/nearley.js:343:27)
    at _parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:110:16)
    at doParse (/src/node_modules/pgsql-ast-parser/src/parser.ts:57:27)
    at Object.parse (/src/node_modules/pgsql-ast-parser/src/parser.ts:60:11)
```

**Comment by oguimbal** [comment]
Should be fixed in ` pgsql-ast-parser@11.0.0`
