### ISSUE TITLE
Help needed in adding the "timestampz" alias for "timestamp with time zone"

### ISSUE THREAD

**Issue by bplower** [oguimbal/pgsql-ast-parser#19]
Hey @oguimbal 👋  Thanks for making this and the pg-mem repos- they're awesome!

I'm working on adding pg-mem to a personal project and had a few migrations that used `timestampz` rather than the more verbose `timestamp with time zone`. I figured this was a good opportunity to give back to the project and add support for `timestampz`, but I'm afraid I'm a bit lost while trying to implement the type alias.

I'm not sure if I'm going in the right direction, but these are changes I've got so far

```diff
diff --git a/src/syntax/base.ne b/src/syntax/base.ne
index 486eb66..e504c04 100644
--- a/src/syntax/base.ne
+++ b/src/syntax/base.ne
@@ -147,6 +147,7 @@ kw_cache -> %word {% notReservedKw('cache')  %}
 kw_cascade -> %word {% notReservedKw('cascade')  %}
 kw_no -> %word {% notReservedKw('no')  %}
 kw_timestamp -> %word {% notReservedKw('timestamp')  %}
+kw_timestampz -> %word {% notReservedKw('timestampz')  %}
 kw_cycle -> %word {% notReservedKw('cycle')  %}
 kw_function -> %word {% notReservedKw('function')  %}
 kw_returns -> %word {% notReservedKw('returns')  %}
diff --git a/src/syntax/create-table.spec.ts b/src/syntax/create-table.spec.ts
index 9b28fe5..ad50d5c 100644
--- a/src/syntax/create-table.spec.ts
+++ b/src/syntax/create-table.spec.ts
@@ -165,6 +165,16 @@ describe('Create table', () => {
         }],
     });
 
+    checkCreateTable(['create table "test" (value timestampz)'], {
+        type: 'create table',
+        name: 'test',
+        columns: [{
+            kind: 'column',
+            name: 'value',
+            dataType: { name: 'timestamp with time zone' },
+        }],
+    });
+
     checkInvalid('create table"test"(value "timestamp" with time zone)');
     checkInvalid('create table"test"(value timestamp with "time" zone)');
 ```

With the keyword added, I'm seeing my new test failing, which makes sense considering some form of alias hasn't been defined:

```
  1) Create table
       parses create table "test" (value timestampz):

      Parser has not returned the expected AST
      + expected - actual

       {
         "columns": [
           {
             "dataType": {
      -        "name": "timestampz"
      +        "name": "timestamp with time zone"
             }
             "kind": "column"
             "name": "value"
           }
      
      at Context.<anonymous> (src/syntax/spec-utils.ts:76:26)
      at processImmediate (internal/timers.js:461:21)
```

However I am admittedly lost now 😅 I took a wild guess and added the word to the data_type_date definition, but this clearly isn't quite right, since it results in the "Ambiguous matches" test failing, saying there are 2 available options.

```diff
diff --git a/src/syntax/base.ne b/src/syntax/base.ne
index 486eb66..e504c04 100644
--- a/src/syntax/base.ne
+++ b/src/syntax/base.ne
@@ -247,6 +248,7 @@ data_type_text
 #https://www.postgresql.org/docs/9.5/datatype-datetime.html
 data_type_date
      ->  (%word {% anyKw('timestamp', 'time') %}) (%kw_with | %word {% kw('without') %}) (%word {% kw('time') %}) (%word {% kw('zone') %})
+     | (%word {% kw('timestampz') %})
     # | word {% kw('date') %}
     # | word {% kw('interval') %}
     # | word {% kw('timestamp') %} 
```

I don't have much experience with ASTs or with moo/nearley, but I think I can get this implemented with a little nudge in the right direction, so any help or info would be much appreciated. Thanks! 🙂

**Comment by oguimbal** [comment]
Hi ! Thanks for trying to contribute, that means a lot :)

Are you sure to be using the latest version of pgsql-ast-parser ? (or pg-mem ?)

Because timestampz is supposed to be supported (it was not in older versions), both by pgsql-ast-parser and by pg-mem.

Actually, the parser is now supposed to support any data type... that's why lines like `# | word {% kw('date') %}`  below the one you modified have been commented: the parser does not check data type explicelly: it now accepts any valid name. 
The only explicit types that are known by the parser are things which are not a valid names but "plain english well known names"  such as `timestamp with timezone`.

<p align="center">
<img width="400" src="https://user-images.githubusercontent.com/8973947/108718937-40692280-751f-11eb-82b3-d4f8015bfccf.png">
</p>

The types that are natively supported by pg-mem are referenced [in pg-catalog/index.ts](https://github.com/oguimbal/pg-mem/blob/master/src/schema/pg-catalog/index.ts), and some type synonyms are [declared here](https://github.com/oguimbal/pg-mem/blob/b1f9af2380da5ea0f462a2c7e2322841a94b20fd/src/datatypes/datatypes.ts#L589-L619) (which is an ugly hack I used when two types implementations are similar enough to be lazy).

For the sake of simplicity, you can see that `timestampz` has been "implemented" as a type synonym of the `timestamp` type (which means that pg-mem has no concept of timezones... its just JS dates):

```typescript
    'timestampz': DataType.timestamp, //  => todo support timestampz
    'timestamp with time zone': DataType.timestamp, //  => todo support timestampz
```

If you'd like timezones implemented, it would mean implement a timezone-aware version of [the timestamp type](https://github.com/oguimbal/pg-mem/blob/b1f9af2380da5ea0f462a2c7e2322841a94b20fd/src/datatypes/t-timestamp.ts), reference it in pg-catalog, and remove the type synonyms.

I did not implement timestampz because:

1) I'm not sure how to unit test it.
2) Lack of time, mostly
3) I live in ~UTC, meaning that I've never seen much difference between timestamp & timestampz... meaning that the ratio `my brain hurts / timezones are useful to me` has always been too high 😁


Do you need timezones implemented ? Or this fallback to timestamp is ok with you ?

ps: I move this issue to pg-mem.
