### ISSUE TITLE
Missing POSIX regex match operators

### ISSUE THREAD

**Issue by erw6f** [oguimbal/pgsql-ast-parser#28]
New upgrade has been very helpful. I found a missing operator:
https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP
```
Error: invalid syntax at line 1 col 21:

  SELECT CASE WHEN $1 ~ '.*' THEN 'something' ELSE 'something else' END
                      ^
Unexpected input (lexer error). Instead, I was expecting to see one of the following:

    - A "op_cast" token
    - A "lbracket" token
    - A "op_member" token
    - A "op_membertext" token
    - A "word" token
    - A "op_exp" token
    - A "star" token
    - A "op_div" token
    - A "op_mod" token
    - A "op_plus" token
    - A "op_minus" token
    - A "op_additive" token
    - A "kw_not" token
    - A "kw_in" token
    - A "kw_not" token
    - A "op_like" token
    - A "op_ilike" token
    - A "op_not_like" token
    - A "op_not_ilike" token
    - A "kw_like" token
    - A "kw_ilike" token
    - A "ops_others" token
    - A "kw_not" token
    - A "kw_is" token
    - A "kw_notnull" token
    - A "kw_is" token
    - A "kw_isnull" token
    - A "kw_is" token
    - A "word" token
    - A "op_compare" token
    - A "op_eq" token
    - A "op_neq" token
    - A "kw_then" token
    - A "kw_and" token
    - A "kw_or" token


    at Parser.feed (https://deno.land/x/nearley@2.19.7-deno/lib/nearley.js:289:27)
    at _parse (parser.ts:110:16)
    at doParse (parser.ts:57:27)
    at parse (parser.ts:60:11)
    at parseFirst (parser.ts:19:19)
```

**Comment by oguimbal** [comment]
Should be ok with `pgsql-ast-parser@7.0.0` 🎉
