### ISSUE TITLE
Column REFERENCES not supported

### ISSUE THREAD

**Issue by LorenzHenk** [oguimbal/pgsql-ast-parser#86]
Defining a foreign key on a column seems to fail:

```sql
CREATE TABLE foo (
    id BIGSERIAL PRIMARY KEY,
    bar_id INTEGER NOT NULL REFERENCES users(id)
);
```

```
Error: Syntax error at line 3 col 29:

      bar_id INTEGER NOT NULL REFERENCES
                              ^
Unexpected kw_references token: "references". Instead, I was expecting to see one of the following:

    - A "kw_constraint" token
    - A "kw_unique" token
    - A "kw_null" token
    - A "kw_default" token
    - A "kw_check" token
    - A "kw_primary" token
    - A "kw_not" token
    - A "comma" token
    - A "rparen" token
    - A "word" token


Occurred while linting example.sql:1
    at Parser.feed (node_modules/nearley/lib/nearley.js:343:27)
    at _parse (node_modules/pgsql-ast-parser/index.js:1866:16)
    at doParse (node_modules/pgsql-ast-parser/index.js:1822:27)
    at Object.tracking (node_modules/pgsql-ast-parser/index.js:270:16)
    at Object.parse (node_modules/pgsql-ast-parser/index.js:1823:96)
```

**Comment by oguimbal** [comment]
Hi !

Fixed in `pgsql-ast-parser@10.5.0` !

Thanks for the report :)
